import type { Metadata } from "next";
import { Providers } from "./providers";
import "./globals.css";
import { Web3Provider } from "./Web3Provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={``}
      >
        <Web3Provider>{children}</Web3Provider>
      </body>
    </html>
  );
}
